#!/usr/bin/env bash
# Local demo backend for the admin CMS: Postgres + PostgREST + a fake Supabase gateway.
# No Supabase project, Docker or Supabase CLI needed. Everything lives in .demo/ (gitignored).
#   bash supabase/demo/start.sh          start (first run creates and seeds the database)
#   bash supabase/demo/start.sh --reset  wipe the demo database and start fresh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DEMO="$ROOT/.demo"
HERE="$ROOT/supabase/demo"
PG_BIN="${PG_BIN:-/Library/PostgreSQL/18/bin}"
PG_PORT=54322
PGRST_PORT=54330
GATEWAY_PORT=54321
PGRST_VERSION=v14.18

export DYLD_LIBRARY_PATH="$(dirname "$PG_BIN")/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
mkdir -p "$DEMO/bin" "$DEMO/logs"

if [[ ! -x "$PG_BIN/initdb" ]]; then
  echo "PostgreSQL binaries not found in $PG_BIN. Install PostgreSQL or set PG_BIN." >&2
  exit 1
fi

if [[ "${1:-}" == "--reset" ]]; then
  bash "$HERE/stop.sh" || true
  rm -rf "$DEMO/pgdata"
fi

# PostgREST binary
if [[ ! -x "$DEMO/bin/postgrest" ]]; then
  case "$(uname -m)" in arm64) arch=aarch64 ;; *) arch=x86-64 ;; esac
  echo "Downloading PostgREST $PGRST_VERSION ($arch)…"
  curl -fsSL "https://github.com/PostgREST/postgrest/releases/download/$PGRST_VERSION/postgrest-$PGRST_VERSION-macos-$arch.tar.xz" \
    | tar -xJ -C "$DEMO/bin"
fi
# The release links Homebrew's libpq; point it at the one shipped with this PostgreSQL install instead
# (DYLD_LIBRARY_PATH is stripped from background processes by macOS, so it can't be relied on).
libpq_link=$(otool -L "$DEMO/bin/postgrest" | awk '/libpq\.5\.dylib/ {print $1}')
if [[ -n "$libpq_link" && ! -e "$libpq_link" ]]; then
  install_name_tool -change "$libpq_link" "$(dirname "$PG_BIN")/lib/libpq.5.dylib" "$DEMO/bin/postgrest" 2>/dev/null
  codesign --force -s - "$DEMO/bin/postgrest" 2>/dev/null
fi

psql() { "$PG_BIN/psql" -h 127.0.0.1 -p "$PG_PORT" -U postgres -d postgres -v ON_ERROR_STOP=1 -q "$@"; }

# Postgres
fresh=0
if [[ ! -d "$DEMO/pgdata" ]]; then
  "$PG_BIN/initdb" -D "$DEMO/pgdata" -U postgres --auth=trust -E UTF8 --locale=C >"$DEMO/logs/initdb.log"
  fresh=1
fi
if ! "$PG_BIN/pg_ctl" -D "$DEMO/pgdata" status >/dev/null 2>&1; then
  "$PG_BIN/pg_ctl" -D "$DEMO/pgdata" -l "$DEMO/logs/postgres.log" -o "-p $PG_PORT -k $DEMO" -w start >/dev/null
fi

if [[ $fresh == 1 ]]; then
  echo "Creating schema and loading pilot content…"
  psql -f "$HERE/bootstrap.sql"
  for f in "$ROOT"/supabase/migrations/*.sql; do psql -f "$f"; done
  psql -f "$ROOT/supabase/seed.sql"
  node "$HERE/accounts.mjs" sql | psql
  psql -f "$HERE/learners.sql"
  psql -f "$HERE/conversations.sql"
fi

JWT_SECRET="eduprep-local-demo-jwt-secret-not-for-production"

start_bg() { # name, command...
  local name=$1; shift
  local pidfile="$DEMO/$name.pid"
  if [[ -f "$pidfile" ]] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then return; fi
  nohup "$@" >"$DEMO/logs/$name.log" 2>&1 &
  echo $! >"$pidfile"
}

PGRST_DB_URI="postgres://authenticator:demo@127.0.0.1:$PG_PORT/postgres" \
PGRST_DB_SCHEMAS=public PGRST_DB_ANON_ROLE=anon PGRST_JWT_SECRET="$JWT_SECRET" \
PGRST_SERVER_PORT=$PGRST_PORT PGRST_DB_CHANNEL_ENABLED=false \
  start_bg postgrest "$DEMO/bin/postgrest"

DEMO_JWT_SECRET="$JWT_SECRET" DEMO_GATEWAY_PORT=$GATEWAY_PORT DEMO_POSTGREST_URL="http://127.0.0.1:$PGRST_PORT" \
  start_bg gateway node "$HERE/gateway.mjs"

# Admin env file (never overwrites one you created yourself)
ENV_FILE="$ROOT/apps/admin/.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  {
    echo "# Generated by supabase/demo/start.sh for the local demo backend."
    echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:$GATEWAY_PORT"
    DEMO_JWT_SECRET="$JWT_SECRET" node "$HERE/gateway.mjs" keys
    echo "API_CORS_ORIGIN=*"
  } >"$ENV_FILE"
  echo "Wrote $ENV_FILE"
fi

for _ in $(seq 1 30); do
  curl -fs -o /dev/null "http://127.0.0.1:$GATEWAY_PORT/rest/v1/" && break
  sleep 0.5
done

echo
echo "Demo backend running: gateway http://localhost:$GATEWAY_PORT (Postgres :$PG_PORT, PostgREST :$PGRST_PORT)"
echo "Admin sign-in: admin@eduprep.africa, reviewer@eduprep.africa or teacher@eduprep.africa. Learner (mobile app): student@eduprep.africa. Password: $(node -e 'import("'"$HERE"'/accounts.mjs").then(m=>console.log(m.DEMO_PASSWORD))')"
echo "Stop with: bash supabase/demo/stop.sh"
