// Generates supabase/seed.sql from content.ts. Run: node supabase/seed/generate.ts
// IDs are derived from stable keys, so re-running the seed updates rows instead of duplicating them.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { exams, subjects, type L } from "./content.ts";
import { uuidFor } from "./ids.ts";

function lit(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function text(t: L): L {
  return Object.fromEntries(Object.entries(t).filter(([, v]) => v && v.trim() !== "")) as L;
}

const out: string[] = [
  "-- Generated by supabase/seed/generate.ts. Do not edit by hand.",
  "-- Original placeholder content for the Cameroon pilot (GCE O/A Level, Probatoire, BAC).",
  "begin;",
];

const subjectId = new Map<string, string>();
for (const s of subjects) {
  const id = uuidFor(`subject:${s.slug}`);
  subjectId.set(s.slug, id);
  out.push(
    `insert into public.subjects (id, slug, name, icon) values (${lit(id)}, ${lit(s.slug)}, ${lit(text(s.name))}, ${lit(s.icon)})
  on conflict (id) do update set name = excluded.name, icon = excluded.icon;`,
  );
}

let counts = { exams: 0, tracks: 0, chapters: 0, lessons: 0, questions: 0 };

for (const exam of exams) {
  const examId = uuidFor(`exam:${exam.slug}`);
  counts.exams++;
  out.push(
    `insert into public.exams (id, country_code, slug, name, description, level, primary_language, program_config, active)
  values (${lit(examId)}, 'CM', ${lit(exam.slug)}, ${lit(text(exam.name))}, ${lit(text(exam.description))}, ${lit(exam.level)}, ${lit(exam.primaryLanguage)}, ${lit(exam.program)}, true)
  on conflict (id) do update set name = excluded.name, description = excluded.description, level = excluded.level, primary_language = excluded.primary_language, program_config = excluded.program_config;`,
  );

  exam.tracks.forEach((track, trackIndex) => {
    const trackId = uuidFor(`track:${exam.slug}:${track.slug}`);
    counts.tracks++;
    out.push(
      `insert into public.exam_tracks (id, exam_id, slug, name, order_index) values (${lit(trackId)}, ${lit(examId)}, ${lit(track.slug)}, ${lit(text(track.name))}, ${trackIndex})
  on conflict (id) do update set name = excluded.name, order_index = excluded.order_index;`,
    );

    track.subjects.forEach(([slug, coefficient], i) => {
      const sid = subjectId.get(slug);
      if (!sid) throw new Error(`Unknown subject ${slug}`);
      out.push(
        `insert into public.track_subjects (track_id, subject_id, coefficient, order_index) values (${lit(trackId)}, ${lit(sid)}, ${coefficient}, ${i})
  on conflict (track_id, subject_id) do update set coefficient = excluded.coefficient, order_index = excluded.order_index;`,
      );
    });

    track.chapters.forEach((chapter, chapterIndex) => {
      const sid = subjectId.get(chapter.subject);
      if (!sid) throw new Error(`Unknown subject ${chapter.subject}`);
      if (!track.subjects.some(([slug]) => slug === chapter.subject)) {
        throw new Error(`Chapter ${chapter.key} uses subject ${chapter.subject} which is not in track ${track.slug}`);
      }
      const chapterId = uuidFor(`chapter:${chapter.key}`);
      counts.chapters++;
      out.push(
        `insert into public.chapters (id, track_id, subject_id, title, order_index, status) values (${lit(chapterId)}, ${lit(trackId)}, ${lit(sid)}, ${lit(text(chapter.title))}, ${chapterIndex}, ${lit(chapter.status ?? "published")})
  on conflict (id) do update set title = excluded.title, order_index = excluded.order_index, status = excluded.status;`,
      );

      chapter.lessons.forEach((lesson, lessonIndex) => {
        counts.lessons++;
        out.push(
          `insert into public.lessons (id, chapter_id, title, body, estimated_minutes, order_index, status) values (${lit(uuidFor(`lesson:${chapter.key}:${lesson.key}`))}, ${lit(chapterId)}, ${lit(text(lesson.title))}, ${lit(text(lesson.body))}, ${lesson.minutes}, ${lessonIndex}, ${lit(lesson.status ?? "published")})
  on conflict (id) do update set title = excluded.title, body = excluded.body, estimated_minutes = excluded.estimated_minutes, order_index = excluded.order_index, status = excluded.status;`,
        );
      });

      for (const q of chapter.questions) {
        const qid = uuidFor(`question:${chapter.key}:${q.key}`);
        counts.questions++;
        const [numericAnswer, numericTolerance] = q.numeric ?? [null, null];
        if (q.type === "numeric" && numericAnswer === null) throw new Error(`${qid} needs a numeric answer`);
        if (q.type !== "numeric" && (q.options ?? []).filter((o) => o[2]).length === 0) {
          throw new Error(`${chapter.key}:${q.key} has no correct option`);
        }
        out.push(
          `insert into public.questions (id, subject_id, chapter_id, type, prompt, difficulty, source_type, numeric_answer, numeric_tolerance, status)
  values (${lit(qid)}, ${lit(sid)}, ${lit(chapterId)}, ${lit(q.type)}, ${lit(text(q.prompt))}, ${q.difficulty}, 'original', ${lit(numericAnswer)}, ${lit(numericTolerance)}, ${lit(chapter.status ?? "published")})
  on conflict (id) do update set type = excluded.type, prompt = excluded.prompt, difficulty = excluded.difficulty, numeric_answer = excluded.numeric_answer, numeric_tolerance = excluded.numeric_tolerance, status = excluded.status;`,
          `insert into public.solutions (question_id, explanation) values (${lit(qid)}, ${lit(text(q.explanation))})
  on conflict (question_id) do update set explanation = excluded.explanation;`,
        );
        (q.options ?? []).forEach(([en, fr, correct], i) => {
          out.push(
            `insert into public.question_options (id, question_id, text, is_correct, order_index) values (${lit(uuidFor(`option:${chapter.key}:${q.key}:${i}`))}, ${lit(qid)}, ${lit(text({ en, fr }))}, ${correct === true}, ${i})
  on conflict (id) do update set text = excluded.text, is_correct = excluded.is_correct, order_index = excluded.order_index;`,
          );
        });
      }
    });
  });
}

out.push("commit;", "");

const target = join(dirname(fileURLToPath(import.meta.url)), "..", "seed.sql");
writeFileSync(target, out.join("\n"));
console.log(`Wrote ${target}`, counts);
